### ISSUE TITLE
backup_player_tables error

### ISSUE THREAD

**Issue by xXxWarAngelxXx** [Akkadius/eqemu-install-v2#1]
![Error](https://user-images.githubusercontent.com/63894482/82681528-c0fe9980-9c02-11ea-97c8-815ebab13337.png)

I hope this is just my issue. But I thought I should post this just in case. Did a fresh install on the v2. And went through all the eqemu_server.pl utilities. And this is the only issue I had come across. Even as a small means of debugging. I tried the backup_player_table three different time blocks of the day.

-WarAngel

**Comment by Akkadius** [comment]
This should be resolved now
